apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testplanning
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: implementation
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicedesk
spec:
  replicas: 3
