apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  template:
    spec:
      containers:
      - name: notification
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  template:
    spec:
      containers:
      - name: devops
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testplanning
spec:
  template:
    spec:
      containers:
      - name: testplanning
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: implementation
spec:
  template:
    spec:
      containers:
      - name: implementation
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicedesk
spec:
  template:
    spec:
      containers:
      - name: servicedesk
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
