apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agents

commonLabels:
  app: agents
  managed-by: kustomize

resources:
  - namespace.yaml

helmCharts:
  - name: agents
    repo: oci://youracr.azurecr.io/helm
    version: 1.0.0
    releaseName: agents
    namespace: agents
    valuesFile: values.yaml
